agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns=[
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
    path('create/', AgentCreateView.as_view(), name='agent-create')
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView, BlogPageView, AboutPageView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('blog/', BlogPageView.as_view(), name='blog'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace='agents')),

    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, 
    LeadDetailView, 
    LeadCreateView, 
    LeadDeleteView, 
    LeadUpdateView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView
)
#from .views import (lead_list, lead_detail, lead_create, lead_update,
#lead_delete, LeadListView, LeadDetailView, LeadCreateView, LeadDeleteView, 
#LeadUpdateView)

#from .views import lead_list

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update')
]

templates/about.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}


<article class="max-w-2xl px-6 py-24 mx-auto space-y-12 dark:bg-gray-800 dark:text-gray-50">
	<div class="w-full mx-auto space-y-4 text-center">
		<p class="text-xs font-semibold tracking-wider uppercase">#О нас</p>
		<h1 class="text-4xl font-bold leading-tight md:text-5xl">Немного о CRM</h1>
		<div class="flex flex-col items-start justify-between w-full md:flex-row md:items-center dark:text-gray-400">
			<div class="flex items-center md:space-x-2">
				<img src="https://source.unsplash.com/75x75/?portrait" alt="" class="w-4 h-4 border rounded-full dark:bg-gray-500 dark:border-gray-700">
				<p class="text-sm">Администратор</p><span id='date-time'></span>
			</div>
			<p class="flex-shrink-0 mt-3 text-sm md:mt-0">Чтение 4 минуты • 3 206 просмотров</p>
		</div>
	</div>
	<div class="dark:text-gray-100">
		<span id="hs_cos_wrapper_post_body" class="hs_cos_wrapper hs_cos_wrapper_meta_field hs_cos_wrapper_type_rich_text" data-hs-cos-general-type="meta_field" data-hs-cos-type="rich_text">
	  
			<div class="hsg-featured-snippet">
				<div class="hsg-featured-snippet__wrapper">
					<h2>Что такое CRM?</h2>
					<div class="hsg-featured-snippet__wrapper--content" data-type="paragraph">
						<p>Управление взаимоотношениями с клиентами (CRM) - это технология управления всеми отношениями и взаимодействиями вашей компании с клиентами и потенциальными клиентами. Цель проста: улучшить деловые отношения для роста вашего бизнеса. Система CRM помогает компаниям поддерживать связь с клиентами, оптимизировать процессы и увеличивать прибыльность.
						</p><br>
						<p>
						Когда люди говорят о CRM, обычно имеют в виду систему CRM, инструмент, который помогает в управлении контактами, управлении продажами, повышении производительности агентов и многом другом. Сейчас CRM-инструменты могут использоваться для управления отношениями с клиентами на протяжении всего жизненного цикла клиента, включая маркетинг, продажи, цифровую коммерцию и взаимодействие с обслуживанием клиентов.
						</p><br>
						<p>
						Решение CRM помогает вам сосредотачиваться на отношениях вашей организации с отдельными людьми - включая клиентов, пользователей услуг, коллег или поставщиков - на протяжении всего их жизненного цикла, включая поиск новых клиентов, завоевание их бизнеса и предоставление поддержки и дополнительных услуг на протяжении всего отношения.</p>
					</p>
					</div>
				</div>
			</div>
			
			<br>
			<h4>Для кого предназначена CRM?</h4><br>
			<p>
				Система CRM дает возможность всем - от продаж и обслуживания клиентов до развития бизнеса, найма, маркетинга и других видов деятельности - эффективнее управлять внешними взаимодействиями и отношениями, которые способствуют успеху. Инструмент CRM позволяет хранить информацию о контактах с клиентами и потенциальными клиентами, определять возможности продаж, регистрировать проблемы обслуживания и управлять маркетинговыми кампаниями, все в одном центральном месте, и делать информацию о каждом взаимодействии с клиентом доступной всем, кто может ее потребовать в вашей компании.
			</p><br>
			<p>
			Благодаря видимости и легкому доступу к данным, становится проще сотрудничать и повышать производительность. Вся ваша компания может видеть, как взаимодействовали с клиентами, что они покупали, когда последний раз покупали, сколько они заплатили и многое другое. CRM может помочь компаниям любого размера достичь роста бизнеса, особенно малому бизнесу, где команды часто должны находить способы сделать больше с меньшими ресурсами.
			</p><br>
			
			
			<h4>Почему CRM важна для вашего бизнеса?</h4><br>
			<p>
				CRM - самая крупная и быстрорастущая категория программного обеспечения для предприятий, и мировые расходы на CRM ожидаются достигнуть 114,4 миллиарда долларов США к 2027 году. Если вашему бизнесу предстоит долгое существование, вам нужна стратегия будущего, ориентированная на ваших клиентов и обеспечиваемая правильной технологией. У вас есть цели по продажам, бизнес-цели и прибыльность. Но как получить актуальную и надежную информацию о вашем прогрессе? Как перевести множество потоков данных, поступающих из продаж, обслуживания клиентов, маркетинга и мониторинга социальных медиа, в полезную информацию для бизнеса?
			</p><br>
	
			<p>
				Система CRM может предоставить вам ясное представление о ваших клиентах. Вы можете видеть все в одном месте - простой настраиваемый инструментарий, который может рассказать вам о предыдущей истории клиента с вами, о состоянии его заказов, о проблемах обслуживания клиентов и многом другом. Вы даже можете выбрать включение информации из их публичной активности в социальных медиа - их предпочтения и антипатии, то, что они говорят и делятся о вас или ваших конкурентах. Маркетологи могут использовать решение CRM для управления и оптимизации кампаний и путей привлечения лидов с использованием подхода на основе данных, и лучше понимать воронку продаж или потоки поступающих лидов, что делает прогнозирование более простым и точным. Вы будете иметь ясное представление о каждой возможности или лиде, показывая вам четкий путь от запросов до продаж. Некоторые из самых больших приростов в производительности и перехода к ориентации на клиента во всей компании могут произойти, когда CRM перестанет быть просто инструментом продаж и маркетинга, и будет внедрена в вашей компании - от финансов до обслуживания клиентов и управления цепочкой поставок. Это помогает гарантировать, что потребности клиентов находятся в центре бизнес-процесса и циклов инноваций.
			</p><br>
	
			<p>
				Хотя системы CRM традиционно использовались как инструменты продаж и маркетинга, обслуживание и поддержка клиентов - это растущий сегмент CRM и ключевой элемент управления всесторонними взаимоотношениями с клиентами. Сегодня клиент может поднять вопрос в одном канале - скажем, в Twitter - а затем переключиться на электронную почту или телефон для его решения в частности. Платформа CRM позволяет управлять запросом через разные каналы, не теряя его, и предоставляет продажам, обслуживанию и маркетингу единую картину клиента для информирования их деятельности. Возможность соединить эти три функции и команды, которые их выполняют, на одной платформе и с одним видом клиента, бесценна для предоставления соответствующих и связанных взаимодействий.
			</p>
			
			<br>
			<!-- <div class="blog-post-body-featured-image"> -->
			<img src="/static/images/salesforce-customer.jpg">
			<figcaption style="text-align:center">Рис. 1 - Источник: https://www.salesforce.com/crm/what-is-crm/</figcaption>
			<!-- </div> -->
			<br>
	
		</span>
	</div>
	
	<div class="pt-12 border-t dark:border-gray-700">
		<div class="flex flex-col space-y-4 md:space-y-0 md:space-x-6 md:flex-row">
			<img src="https://source.unsplash.com/75x75/?portrait" alt="" class="self-center flex-shrink-0 w-24 h-24 border rounded-full md:justify-self-start dark:bg-gray-500 dark:border-gray-700">
			<div class="flex flex-col">
				<h4 class="text-lg font-semibold">Администратор</h4>
				<p class="dark:text-gray-400">Это небольшое описание профиля администратора. Некоторые изображения использованы в качестве справочных материалов из source.unsplash.com</p>
			</div>
		</div>
		<div class="flex justify-center pt-4 space-x-4 align-center">
			<a rel="noopener noreferrer" href="https://github.com/Kanagat01" target="_blank" aria-label="GitHub" class="p-2 rounded-md dark:text-gray-100 hover:dark:text-violet-400">
				<svg viewBox="0 0 496 512" xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 fill-current">
					<path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path>
				</svg>
			</a>
			<a rel="noopener noreferrer" href="https://github.com/Kanagat01" target="_blank" aria-label="Dribble" class="p-2 rounded-md dark:text-gray-100 hover:dark:text-violet-400">
				<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 fill-current">
					<path d="M256 8C119.252 8 8 119.252 8 256s111.252 248 248 248 248-111.252 248-248S392.748 8 256 8zm163.97 114.366c29.503 36.046 47.369 81.957 47.835 131.955-6.984-1.477-77.018-15.682-147.502-6.818-5.752-14.041-11.181-26.393-18.617-41.614 78.321-31.977 113.818-77.482 118.284-83.523zM396.421 97.87c-3.81 5.427-35.697 48.286-111.021 76.519-34.712-63.776-73.185-116.168-79.04-124.008 67.176-16.193 137.966 1.27 190.061 47.489zm-230.48-33.25c5.585 7.659 43.438 60.116 78.537 122.509-99.087 26.313-186.36 25.934-195.834 25.809C62.38 147.205 106.678 92.573 165.941 64.62zM44.17 256.323c0-2.166.043-4.322.108-6.473 9.268.19 111.92 1.513 217.706-30.146 6.064 11.868 11.857 23.915 17.174 35.949-76.599 21.575-146.194 83.527-180.531 142.306C64.794 360.405 44.17 310.73 44.17 256.323zm81.807 167.113c22.127-45.233 82.178-103.622 167.579-132.756 29.74 77.283 42.039 142.053 45.189 160.638-68.112 29.013-150.015 21.053-212.768-27.882zm248.38 8.489c-2.171-12.886-13.446-74.897-41.152-151.033 66.38-10.626 124.7 6.768 131.947 9.055-9.442 58.941-43.273 109.844-90.795 141.978z"></path>
				</svg>
			</a>
			<a rel="noopener noreferrer" href="#" aria-label="Twitter" class="p-2 rounded-md dark:text-gray-100 hover:dark:text-violet-400">
				<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 fill-current">
					<path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path>
				</svg>
			</a>
			<a rel="noopener noreferrer" href="#" aria-label="Email" class="p-2 rounded-md dark:text-gray-100 hover:dark:text-violet-400">
				<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 fill-current">
					<path d="M464 64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V112c0-26.51-21.49-48-48-48zm0 48v40.805c-22.422 18.259-58.168 46.651-134.587 106.49-16.841 13.247-50.201 45.072-73.413 44.701-23.208.375-56.579-31.459-73.413-44.701C106.18 199.465 70.425 171.067 48 152.805V112h416zM48 400V214.398c22.914 18.251 55.409 43.862 104.938 82.646 21.857 17.205 60.134 55.186 103.062 54.955 42.717.231 80.509-37.199 103.053-54.947 49.528-38.783 82.032-64.401 104.947-82.653V400H48z"></path>
				</svg>
			</a>
		</div>
	</div>
</article>




{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>CRM</title>
		<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
		<link href = "{% static 'css/styles.css' %}" rel="stylesheet" />
		<link href = "{% static 'css/post-min.css' %}" rel="stylesheet" />
		<script src="{% static 'js/main.js' %}" type="text/javascript"></script>  

		<!-- <style>
			a.cta_button{-moz-box-sizing:content-box !important;-webkit-box-sizing:content-box !important;box-sizing:content-box !important;vertical-align:middle}.hs-breadcrumb-menu{list-style-type:none;margin:0px 0px 0px 0px;padding:0px 0px 0px 0px}.hs-breadcrumb-menu-item{float:left;padding:10px 0px 10px 10px}.hs-breadcrumb-menu-divider:before{content:'›';padding-left:10px}.hs-featured-image-link{border:0}.hs-featured-image{float:right;margin:0 0 20px 20px;max-width:50%}@media (max-width: 568px){.hs-featured-image{float:none;margin:0;width:100%;max-width:100%}}.hs-screen-reader-text{clip:rect(1px, 1px, 1px, 1px);height:1px;overflow:hidden;position:absolute !important;width:1px}
		</style> -->
		
		<!-- <link rel="stylesheet" href="https://blog.hubspot.com/wt-assets/static-files/2.1.19/core-nav/styles.css"> -->
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/template_assets/77591971379/1673638882938/_Web_Team_Assets/Blog/templates/partials/blog-international-navigation/navigation.min.css">
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/module_assets/77591971357/1674594577100/module_77591971357_read-time-bar.min.css">
		<!-- <link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/template_assets/77591971382/1675080057451/_Web_Team_Assets/Blog/templates/pages/post/post.min.css"> -->
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/module_assets/82682696854/1674594576690/module_82682696854_public-facing-updated-date.min.css">
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/module_assets/68123102211/1675080053476/module_68123102211_post-header.min.css">
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/module_assets/69920707401/1675362743981/module_69920707401_social-share-on-page.min.css">
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/module_assets/69920707403/1674594577558/module_69920707403_suggested-content.min.css">
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/module_assets/77591239588/1674594577278/module_77591239588_social-share-popover.min.css">
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/module_assets/70928313376/1674744971632/module_70928313376_exit-intent-popup.min.css">
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/module_assets/70928313387/1674594578563/module_70928313387_sticky-cta.min.css">
		<link rel="stylesheet" href="https://blog.hubspot.com/hs-fs/hub/53/hub_generated/template_assets/67636986656/1668701964851/_Web_Team_Assets/Website/assets/css/multi-step-offers-form.min.css">
	
		
		






	</head>
	<body>
		<div class = "max-w-7xl mx-auto">
			{% include 'navbar.html' %}
			{% block content %}
			{% endblock content %}
		</div>
		{% include "scripts.html" %}
	</body>
	</html>

templates/landing.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="static/images/crm-logo.svg">
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"> CRM написанный на Django </h1>
      <p class="mb-8 leading-relaxed">
      	Эта CRM поможет вам управлять вашими лидами.
      </p>
      <div class="flex justify-center">
	<a href="{% url 'about' %}"><button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg" >Узнать больше</button></a>
	<a href="{% url 'login' %}"><button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Начать работать</button></a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="hover:text-blue-500 flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" href="/">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
	      <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl"> CRM </span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a class="hover:text-blue-500 pr-5"  href="\" >Главная</a>
      <a class="hover:text-blue-500 pr-5"  href="{% url 'about' %}">О нас</a>
      <a class="hover:text-blue-500 pr-5"  href="{% url 'blog' %}" >Блог</a>
      {% if not request.user.is_authenticated %}
      <a class="hover:text-blue-500 pr-5"  href="{% url 'signup' %}" class="mr-5 hover:text-gra-900">Зарегистрироваться</a>
      {% else %}
          {% if request.user.is_organizer %}
              <a class="hover:text-blue-500 pr-5" href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gra-900">Агенты</a>
          {% endif %}
          <a class="hover:text-blue-500 pr-5" href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gra-900">Лиды</a>
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
        Пользователь: {{ request.user.username }}
        <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Выйти с аккаунта
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
        </a>
    {% else %}
        <a  href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Вход
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
        </a>
    {% endif %}
  </div>
</header>

templates/scripts.html
{% load static %}
<script src="{% static 'js/main.js' %}"></script>